CREATE TABLE Quiz( 
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CATEGORY VARCHAR2(20) CHECK (CATEGORY IN ('History', 'Geography', 'Politics', 'Conservation', 'Celebrities', 'Law', 'Sport')),
    QUESTION_TYPE VARCHAR2(10) CHECK (QUESTION_TYPE IN ('Multiple', 'Binary', 'Video')),
    DIFFICULTY VARCHAR2(10) CHECK (DIFFICULTY IN ('Beginner', 'Expert')),
    DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SavedScore(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	QUIZ_ID INTEGER NOT NULL,
    SCORE INTEGER NOT NULL,
	FOREIGN KEY(QUIZ_ID) REFERENCES Quiz(ID)
);